services:
  postgres:
    restart: unless-stopped
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak

  keycloak:
    restart: unless-stopped
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: postgres
      DB_USER: keycloak
      BD_PASSWORD: password
      DB_ADDR: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: pass
